apiVersion: v1
kind: ConfigMap
metadata:
  name: python-auto-scripts
  namespace: ansible
apiVersion: v1
data:
auto-check.py: |-
    # -*- coding: utf-8 -*-

    import paramiko
    import time
    import os
    import sys

    # ==========================================
    # USERNAME and PASSWORD setting
    # CHANGE THESE VALUES
    # ==========================================
    USERNAME = "admin"
    PASSWORD = "admin"
    # ==========================================

    # File paths
    DEVICE_LIST_FILE = "device_list.txt"
    COMMANDS_FILE = "commands.txt"
    OUTPUT_DIR = "check_results"

    def load_file(filename):
        """Loads lines from a text file into a list."""
        try:
            # Python 3에서는 encoding을 명시하는 것이 좋습니다.
            with open(filename, 'r', encoding='utf-8') as f:
                lines = [line.strip() for line in f if line.strip() and not line.startswith('#')]
                return lines
        except IOError:
            print(f"[ERROR] File '{filename}' not found. Please check the file path.")
            sys.exit(1)

    def run_periodic_check():
        """Connects to devices via SSH, executes commands, and saves results."""

        # 1. Load files
        devices = load_file(DEVICE_LIST_FILE)
        commands = load_file(COMMANDS_FILE)

        if not devices:
            print("[WARNING] Device list is empty. Exiting.")
            return

        # 2. Create output directory
        if not os.path.exists(OUTPUT_DIR):
            os.makedirs(OUTPUT_DIR)
            print(f"[{OUTPUT_DIR}] directory created.")

        total_devices = len(devices)
        print(f"\n--- Automated Check Started (Total {total_devices} devices) ---")

        for i, device_ip in enumerate(devices):
            print(f"\n[{i+1}/{total_devices}] Attempting connection to: {device_ip}")

            output_filename = os.path.join(OUTPUT_DIR, f"{device_ip}_check_result.txt")

            ssh = None # Initialize variable
            try:
                ssh = paramiko.SSHClient()
                ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

                # SSH connect
                ssh.connect(device_ip, username=USERNAME, password=PASSWORD, timeout=10)
                print(f"   -> Connection successful: {device_ip}")

                current_time = time.strftime('%Y-%m-%d %H:%M:%S')
                
                # Python 3에서는 encoding='utf-8' 권장
                with open(output_filename, 'w', encoding='utf-8') as outfile:
                    outfile.write(f"--- Arista Device Check Result: {device_ip} ---\n")
                    outfile.write(f"--- Start Time: {current_time} ---\n\n")

                    # 3. Execute commands
                    for j, command in enumerate(commands):
                        print(f"   -> Executing command ({j+1}/{len(commands)}): {command}")
                        outfile.write("\n======================================================\n")
                        outfile.write(f"Command: {command}\n")
                        outfile.write("======================================================\n")

                        # Execute command
                        stdin, stdout, stderr = ssh.exec_command(command)

                        # Read and write result (stdout)
                        # errors='ignore'를 추가하여 알 수 없는 특수문자로 인한 멈춤 방지
                        result = stdout.read().decode('utf-8', errors='ignore')
                        outfile.write(result)

                        # Check for errors (stderr)
                        error = stderr.read().decode('utf-8', errors='ignore')
                        if error:
                            outfile.write(f"\n[Error Output]:\n{error}\n")

                        time.sleep(0.5)

                print(f"   -> Commands completed. Results saved to: {output_filename}")

            except paramiko.AuthenticationException:
                print(f"   [Connection Failed] Authentication Error (ID/PW): {device_ip}")
                with open(os.path.join(OUTPUT_DIR, "error_log.txt"), 'a', encoding='utf-8') as err_log:
                    err_log.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] Auth Failed: {device_ip}\n")
            
            except paramiko.SSHException as e:
                print(f"   [Connection Failed] SSH Error: {device_ip} - {e}")
                with open(os.path.join(OUTPUT_DIR, "error_log.txt"), 'a', encoding='utf-8') as err_log:
                    err_log.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] SSH Error: {device_ip} - {e}\n")
            
            except Exception as e:
                print(f"   [Connection Failed] General Error: {device_ip} - {e}")
                with open(os.path.join(OUTPUT_DIR, "error_log.txt"), 'a', encoding='utf-8') as err_log:
                    err_log.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] General Error: {device_ip} - {e}\n")

            finally:
                # Close SSH connection
                if ssh:
                    ssh.close()

        print("\n--- Automated Check Completed ---")


    if __name__ == "__main__":
        # 필요한 라이브러리 설치 안내: pip install paramiko
        run_periodic_check()
