apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ansible-manage-node
  name: ansible-manage-node
  namespace: ansible
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ansible-manage-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ansible-manage-node
    spec:
      containers:
      - image: ghcr.io/zpzg333/auto-check:latest
        command: ["/bin/sh", "-c", "sleep infinity"]
        imagePullPolicy: Always
        name: auto-check
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: py
          mountPath: /ansible/py-auto-check/auto-check.py
          subPath: auto-check.py
        - name: command
          mountPath: /ansible/py-auto-check/commands.txt
          subPath: commands.txt
        - name: devicelist
          mountPath: /ansible/py-auto-check/device_list.txt
          subPath: device_list.txt
      imagePullSecrets:
      - name: ghcr-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

      volumes:
      - name: py
        configMap: 
          name: python-auto-scripts
          items:
          - key: auto-check.py
            path: auto-check.py
      - name: command
        configMap: 
          name: python-auto-scripts-command
          items:
          - key: commands.txt
            path: commands.txt
      - name: devicelist
        configMap: 
          name: python-auto-scripts-devicelist
          items:
          - key: device_list.txt
            path: device_list.txt           
status: {}
