apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ansible-manage-node
  name: ansible-manage-node
  namespace: ansible
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ansible-manage-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ansible-manage-node
    spec:
      containers:
      - image: ghcr.io/zpzg333/auto-check:latest
        imagePullPolicy: Always
        name: auto-check
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
