apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ansible-manage-node
  name: ansible-manage-node
  namespace: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-manage-node
  template:
    metadata:
      labels:
        app: ansible-manage-node
    spec:
      containers:
      - image: ghcr.io/zpzg333/auto-check:latest
        command: 
          - "/bin/sh"
          - "-c"
          - |
            cd /ansible/ansible/reports
            python3 -m http.server 8080 & 
            sleep infinity
        imagePullPolicy: Always
        name: auto-check
        volumeMounts:
        # 1. 파이썬 스크립트 폴더 (Live Update 가능)
        - name: py-scripts-vol
          mountPath: /ansible/py-auto-check
        
        # 2. Ansible 설정 폴더 (Live Update 가능)
        - name: ansible-cfg-vol
          mountPath: /ansible/ansible # ansible.cfg 위치
        - name: ansible-hosts-vol
          mountPath: /ansible/ansible/inventory # inventory 위치
        - name: ansible-playbook-vol
          mountPath: /ansible/ansible/playbooks # playbook 위치
        - name: ansible-template-vol
          mountPath: /ansible/ansible/templates # jinja2 위치
        - name: reports-temp
          mountPath: /ansible/ansible/reports

      imagePullSecrets:
      - name: ghcr-secret
      
      volumes:
      # ConfigMap과 Volume 연결 시 items를 생략하면 전체 파일이 폴더로 들어갑니다.
      - name: py-scripts-vol
        configMap:
          name: python-auto-scripts
      - name: ansible-cfg-vol
        configMap:
          name: ansible.cfg
      - name: ansible-hosts-vol
        configMap:
          name: hosts.ini
      - name: ansible-playbook-vol
        configMap:
          name: ansible-playbook-config
      - name: ansible-template-vol
        configMap:
          name: template.j2
      - name: reports-temp
        emptyDir: {}
