apiVersion: v1
kind: Service
metadata:
  labels:
    app: ansible-manage-node
  name: ansible-manage-node
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.203.63
  namespace: ansible
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 22
    name: ssh-port
    protocol: TCP
    targetPort: 22
  - port: 8080
    name: testweb
    protocol: TCP
    targetPort: 8080
  selector:
    app: ansible-manage-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
