apiVersion: v1
kind: Service
metadata:
  labels:
    app: ansible-manage-node
  name: ansible-manage-node
  namespace: ansible
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ansible-manage-node
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
